name: Human Who Codes | Ichroman Raditya Duwila
description: >
    Human Who Codes
about: >
    

master_repo: false
url: "https://ichromanrd-blog.herokuapp.com/"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 5

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           whitepaper
  avatar:         "https://tinyurl.com/y4kww8wy"
  email:          "ichromanraditya.duwila@gmail.com"
  # Social networking links used in footer. Update and remove as you like.
  twitter: ichromanrd
  github: https://github.com/ichromanrd
  stackexchange: 
  linkedin: https://www.linkedin.com/in/ichromanrd
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
